#!/usr/bin/env bash
# Script that installs, configures and runs web servers web-02 and web-01
# Custom HTTP header name is XServed-By
# Custome HTTP value is the hostname of the running server
# shellcheck disable=SC2154,SC2024

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html /var/www/error
sudo chmod -R 755 /var/www
sudo echo 'Hello World!' > /var/www/html/index.html
sudo echo -e "Ceci n'est pas une page" > /var/www/error/404.html

SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.html index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
		add_header X-Served-By \$hostname;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://github.com/DanielOkyere permanent;
	}
	error_page 404 /404.html;
	location = /404.html {
		root /var/www/error/;
		internal;
		add_header X-Served-By \$hostname;
	}
}"
bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"
if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi
