#!/usr/bin/env bash
# Script which installs and configures HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Installs and configures HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  koomson-frontend
        bind *:80
        mode http
        default_backend koomson-backend
backend koomson-backend
        balance roundrobin
        server 194883-web-01 54.174.79.17:80 check
        server 194883-web-02 54.236.66.32:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
