#!/usr/bin/env bash
# Script which displays 'To infinity and beyond' indefinitely
# Add sleep 2 in between each iteration of the loop.

while true
do
    echo "To infinity and beyond"
    sleep 2
done
