#!/usr/bin/env bash
# Script which displays 'To infinity and beyond' indefinitely and,
# Adds a sleep 2 in between each iteration of the loop.

trap 'echo "I am invincible!!!"' SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done
